Repository openPMD/openPMD-standard, pull requests merged in 2020-10, with the labels that each got.

#183 New Extension: BeamPhysics
  EXT_BeamPhysics.md
Labels: EXT: BeamPhysics, minor change

#216 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#229 BeamPhysics: Minor syntax and description fixes.
  EXT_BeamPhysics.md
Labels: EXT: BeamPhysics, revision change

#215 axisLabels: fix markdown formatting
  STANDARD.md
Labels: revision change

#204 Authors: Update Year to 2020
  AUTHORS.md
Labels: revision change
