Repository openPMD/openPMD-standard, pull requests merged in 2021-02, with the labels that each got.

#233 Fix minor beam physics
  EXT_BeamPhysics.md
Labels: EXT: BeamPhysics, documentation

#230 Wavefront ext for 2.0.0
  EXT_WAVEFRONT.md
Labels: EXT: New?

#240 Particle ID: Relax Type
  STANDARD.md
Labels: EXT: ED-PIC, major change

#242 EXT: ParticleWeighting
  EXT_ED-PIC.md
  EXT_ParticleWeighting.md
  STANDARD.md
Labels: EXT: ED-PIC, EXT: New?, major change

#245 Authors: 2021
  AUTHORS.md
Labels: documentation

#247 Fix typo: homogeneous
  STANDARD.md
Labels: revision change

#244 Data-Format Specific Conventions
  FORMAT_ADIOS.md
  FORMAT_HDF5.md
  FORMAT_JSON.md
  README.md
  STANDARD.md
Labels: documentation, minor change

#241 Base: Link BeamPhysics & Wavefront Extension
  STANDARD.md
Labels: EXT: New?, revision change
